name: Create GitHub Release
run-name: Create GitHub release by @${{ github.actor }}
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
  
      - name: Create release
        uses: softprops/action-gh-release@v1