name: Create GitHub Release
run-name: Create GitHub release by @${{ github.actor }}
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Check if version has been updated
        id: version_check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          file-name: ./packages/moysklad-ts/package.json
      
      - name: Version update detected
        if: steps.version_check.outputs.changed == 'true'
        run: 'echo "Version change found, creating new release! New version: ${{ steps.version_check.outputs.version }} (${{ steps.version_check.outputs.type }})"'

      - name: Install dependencies
        if: steps.version_check.outputs.changed == 'true'
        run: pnpm install
      - name: Release
        uses: softprops/action-gh-release@v1
        if: steps.version_check.outputs.changed == 'true'